"""changed to Date

Revision ID: e70f94b49f53
Revises: b7109d9cabb6
Create Date: 2024-11-03 20:07:21.355716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70f94b49f53'
down_revision = 'b7109d9cabb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="date::date"  # Explicit cast
        )

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column(
            'dob',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="dob::date"  # Explicit cast
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
